#3.8放眼世界
places=['Paris', 'Chengdu', 'Nanjing', 'Sanya', 'Dali']
print(places)
print(sorted(places))
print(places)
print(sorted(places,reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
